### PR TITLE
fix(installer): fix scoop on windows

### PR DESCRIPTION
**Pull request by StarNumber12046**
Automatically install scoop using the -RunAsAdmin flag on the get.scoop.sh

### CODE REVIEW

**Comment by jdhao** [comment]
I am not familiar with powershell, why the echo command? Have you tested this command?

**Comment by StarNumber12046** [comment]
Yes I did

**Comment by StarNumber12046** [comment]
The | powershell executes what echo printed

**Comment by StarNumber12046** [comment]
I messed up, will fox in the next commit

**Comment by jdhao** [comment]
The scoop install guide has instruction on installing scoop [here](https://github.com/ScoopInstaller/Install#typical-installation). There is no need to use admin rights. In fact, it is not encouraged. If you have specific needs, you can customize yourself.

**Pull request closed without merging**
