### PR TITLE
Manual and automatic installations hyperlinks.

### PR DESCRIPTION
**Pull request by Milo46**
Please, let the people (like me) know that there is an automatic installation.

### CODE REVIEW

**Comment by jdhao** [comment]
Actually, the automatic installation does not install terminal emulators or patched font. Maybe I can put it at the forefront of the doc?

**Comment by Milo46** [comment]
Moving that on top would also work. Just so people could know they don't have to install everything piece by piece.

**Comment by jdhao** [comment]
okay, I will close your PR and rework it a bit. Anything else you would like to change?

**Comment by Milo46** [comment]
I don't think so. That's the only thing.

**Pull request closed without merging**
