### PR TITLE
Add ltex-ls support to lsp.

### PR DESCRIPTION
**Pull request by bldur**
https://valentjn.github.io/ltex/ltex-ls/installation.html

### CODE REVIEW

**Comment by jdhao** [comment]
I am using vimtex for now. It provides completion. I do not see a point in using ltex vs vimtex.

**Comment by bldur** [comment]
It's a grammar checker, it doesn't replace vimtex. It is just that it understand latex and wont confuse this with text.

https://languagetool.org/

**Comment by jdhao** [comment]
Currently I am using [vim-grammarous](https://github.com/rhysd/vim-grammarous), I think the two plugins are having some overlap in function. Need to consider whether it is preferrable to use ltex-ls.

**Comment by bldur** [comment]
This pull request is just the minimum needed in lsp.lua for ltex-ls to run with no tuning or tweaking done.
While allowing mix of american and british english is debateable for sure.

And does that if.executeable, so should be fine?

**Comment by jdhao** [comment]
Thanks, I need to evaluate how to better langtool, if this is better, I will remove vim-grammarous and integrate this. Of course, there need to be other modifications.

**Comment by jdhao** [comment]
Please tidy the indent of the code. There is currently some indentation issues. I think I can merge this and made mofications later.

**Comment by bldur** [comment]
to my eyes it looks identical in indent style to the others, maybe it is the capabilities line under, and newline not needed?
thought it made the settings and language string more clear.

**Comment by bldur** [comment]
think that does it, and thanks! new to this, and didn't know of grammarous, not sure if i have still found it.
but lspconfig seem the right contemporary 2022 to use languagetool with nvim.

**Comment by jdhao** [comment]
Thanks for this PR, I will evaluate this vs vim-grammarous when I have time.

**Comment by bldur** [comment]
I turned on underline and highlight.

https://ibb.co/PNfw0Wy

what it looks like with the simple addition, so minus underline, and warnings and info in signcolumn.

if ltex-ls / ltex-cli works and is found, LspStart works with this block.

Excited about the prospect of better integration and consideration, thanks!

**Pull request merged**
