### PR TITLE
fix language selector error in Android (termux) user

### PR DESCRIPTION
**Pull request by c0del1ar**
This is fixed error for language selection on Android (termux) users

### CODE REVIEW

**Comment by jdhao** [comment]
I thought `UTF-8` and `utf-8` make no difference, the library will normalize the case internally. NO?

**Comment by c0del1ar** [comment]
> I thought `UTF-8` and `utf-8` make no difference, the library will normalize the case internally. NO?
> 
> P.S. Are you really using this config on Android? There are several dependencies that I am not sure can work in termux.

No it isn't.

I have already tested it in termux Android. it works normally (although there are some unreadable libs maybe but no error message on configuration) except that language string. it should be "UTF-8" read from terminal 'local' environment vars.

**Comment by jdhao** [comment]
I am not sure if you can install all dependencies of this config on termux, and I do not use termux personally. If this is only about language setting, maybe I can change it to `UTF-8`, on macOS, the case makes no difference.

**Comment by c0del1ar** [comment]
oh yeah.. if you talking about the all of dependencies, i don't know that if it can run or not. because the major of dependencies is totally works for me. i can help with termux configuration.

Screenshot_20221008_231018

**Comment by jdhao** [comment]
I am not inclined to include support for android as I do not use it. But I can change the language settings if `UTF-8` also works on Windows. Does that work for you?

**Comment by c0del1ar** [comment]
No need, I used arch btw, totally works.

**Pull request closed without merging**
